Sandun
jbllona/458project pull request #1
Opened 2018-05-26 20:56 UTC by sandunr

Comments in the Network class and few small changes....

2018-05-26 21:02 UTC, jbllona approved these changes

2018-05-26 21:04 UTC, jbllona commented on Network.py
> +        self.nodes = {}
edges was being used in the simulation file, and viruses file. Did you change it's name there too?

2018-05-26 21:05 UTC, jbllona requested changes
change the use of edges to nodes in other files that use it

2018-05-26 23:25 UTC, sandunr commented
Okay.. made the changes

2018-05-27 00:50 UTC, jbllona approved these changes

2018-05-27 00:51 UTC, merged